# This is a basic workflow to help you get started with Actions

name: Delete Deployments

# Controls when the workflow will run
on:
  delete:
    branches-ignore:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
    delete:
      runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        - uses: strumwolf/delete-deployment-environment@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            environment: quyyeungoc
            onlyRemoveDeployments: true
     
